name: mybench

up:
  - go: 1.22.1
  # Why not isogun?  because I was having problems with >10 connections
  - podman
  - custom:
      name: Start services
      met?: bin/mysql-healthy
      meet: bin/start-services
      down: podman-compose down
